language: csharp
solution: IBM.WatsonDeveloperCloud.sln
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-preview2-003121
env:
  - DOTNETCORE=1 repo_token=RAjHbC5h4Basi3mqsjtxqTAmxG0SeX7Ru COVERALLS_REPO_TOKEN=l3nZXQA47cVHWucS5LK20u28aer1QZT4zcgFo2LZAOn4v1CtRjrXOomdhvJG95bD

mono:  
  - latest
os:  
  - linux

before_install:
  - chmod +x gradlew
 
script:
  - dotnet restore && dotnet build **/project.json
  - chmod a+x coverage.sh
  - chmod a+x coveralls.sh