version: 0.0.{build}-alpha
image: Visual Studio 2015
platform: Any CPU
clone_folder: c:\projects\wdc-dotnet-standard-sdk
environment:
  COVERALLS_REPO_TOKEN: 1cSKppqhSVXjbnI4nPZsn9imEIwEHtuTy
install:
  - nuget install OpenCover
  - nuget install ReportGenerator
  - nuget install coveralls.net
build_script:
- ps: >-
    dotnet restore

    dotnet build **/project.json
test:
  # assemblies to test
  assemblies:
    - '**\*.UnitTests.dll'
