version: 0.0.{build}-alpha
image: Visual Studio 2015
platform: Any CPU
environment:
  COVERALLS_REPO_TOKEN: 1cSKppqhSVXjbnI4nPZsn9imEIwEHtuTy
build_script:
- ps: >-
    dotnet restore

    dotnet build **/project.json
test:
  # assemblies to test
  assemblies:
    - '**\*.UnitTests.dll'
after_test:
  - bash chmod +x coverage.sh
  - bash chmod +x coveralls.sh
  - bash coverage.sh
  - bash coveralls.sh
